#pragma once

#define IDX_TEMPERATURE 0
#define IDX_HUMIDITY 1
#define IDX_TEMPERATURE_WEATHERSTATION 2
#define IDX_HUMIDITY_WEATHERSTATION 3
#define NUM_RAW_INPUTS 4
#define C22_WINDOW_SIZE 40

#define C22_N_FEATURES 24
