#pragma once

#define IDX_TEMPERATURE 0
#define IDX_HUMIDITY 1
#define IDX_TEMPERATURE_WEATHERSTATION 2
#define IDX_HUMIDITY_WEATHERSTATION 3
#define NUM_RAW_INPUTS 4
#define HJORTH_WINDOW_SIZE 10

#define HJORTH_N_FEATURES 12
